// harry-todo-list/src/app/components/list-item.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import { CommonModule } from '@angular/common';
import {ItemModel} from '../models';

@Component({
  selector: 'app-list-item',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="item" (click)="deleteItem.emit()">
      <div class="img">
        <img [src]="imgPath"/>
      </div>
      <span>{{item.text}}</span>
    </div>

  `,
  styles: [
  ]
})
export class ListItemComponent {
  @Input() item!: ItemModel;
  @Output() deleteItem = new EventEmitter();

  public get imgPath() {
    return `/assets/images/${this.item.imgUrl}`;
  }
}

// harry-todo-list/src/components/ListItem.tsx
import React from 'react';
import {ItemModel} from '../models.ts';

interface ListItemProps {
    item: ItemModel,
    deleteItem: () => void
}
export const ListItem: React.FC<ListItemProps> = ({item, deleteItem}) => {

    const imgPath = `/images/${item.imgUrl}`;

    return (
        <div className="item" onClick={deleteItem}>
            <div className="img">
                <img src={imgPath}/>
            </div>
            <span>{item.text}</span>
        </div>
    )
}
