// harry-todo-list/src/app/app.component.ts
import {Component, inject} from '@angular/core';
import { CommonModule } from '@angular/common';
import {ApiService} from './api.service';
import {ListComponent} from './components/list.component';
import {ModalComponent} from './components/modal.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ListComponent, ModalComponent],
  template: `
    <div class="container">
      <h1>Harry's todo-list</h1>
      <ng-container *ngIf="api.init$ | async">
        <app-list></app-list>
        <app-modal></app-modal>
      </ng-container>
    </div>
  `,
  styles: [
  ],
})
export class AppComponent {
  public api = inject(ApiService);
}

// harry-todo-list/src/App.tsx
import {init} from './api.ts';
import {Page} from './components/Page.tsx';
import {useEffect, useState} from 'react';

function App() {
    const [loaded, setLoaded] = useState(false);

    useEffect(() => {
        init().then(() => setLoaded(true));
    }, []);

  return (
      <div className="container">
          <h1>Harry's todo list</h1>
          {loaded && <Page/>}
      </div>
  );
}

export default App
